zerodine_make_someone_happy:
    resource: "@ZerodineMakeSomeoneHappyBundle/Controller/"
    type:     annotation

login_check:
    path: /login_check

logout:
    path:   /logout

_index:
    path:   /
    defaults: { _controller: ZerodineMakeSomeoneHappyBundle:Default:index }