#zerodine_make_someone_happy:
#    resource: "@ZerodineMakeSomeoneHappyBundle/Controller/"
#    type:     annotation

users:
    type:     rest
    prefix: /api
    resource: Zerodine\Bundle\MakeSomeoneHappyBundle\Controller\PersonController

circles:
    type:     rest
    prefix: /api
    resource: Zerodine\Bundle\MakeSomeoneHappyBundle\Controller\CircleController

#login_check:
#    path: /login_check

#logout:
#    path:   /logout

#_index:
#    path:   /
#    defaults: { _controller: ZerodineMakeSomeoneHappyBundle:Default:index }