security:
    encoders:
        Zerodine\Bundle\MakeSomeoneHappyBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        user_provider:
            id: zerodine.user.provider


    firewalls:
        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        secured_area:
            pattern:    ^/
            form_login:
                provider: user_provider
                check_path: login_check
                login_path: login
            logout:
                path:   logout
                target: login
            anonymous: ~

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            form_login:
                provider: user_provider
                check_path: login_check
                login_path: login
            anonymous: true

    access_control:
        - { path: ^/oauth/vs/tokeninfos, roles: [ IS_AUTHENTICATED_ANONYMOUSLY]}
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }