services:
    user.subscriber:
        class: Zerodine\Bundle\MakeSomeoneHappyBundle\EventListener\UserSubscriber
        calls:
            - [ setEncoderFactory, [@security.encoder_factory] ]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    zerodine.user.manager:
        class: "Doctrine\ORM\EntityManager"
        arguments: [ "%zerodine.entity.user.class%" ]
        factory_service:  doctrine
        factory_method: getManagerForClass

    zerodine.user.repository:
        class: "Zerodine\Bundle\MakeSomeoneHappyBundle\Repository\UserRepository"
        arguments: [ "%zerodine.entity.user.class%" ]
        factory_service:  zerodine.user.manager
        factory_method: getRepository

    zerodine.user.provider:
        class: "%zerodine.user.provider.class%"
        arguments: [ "@zerodine.user.repository" ]

    zerodine.cors_listener:
        class: Zerodine\Bundle\MakeSomeoneHappyBundle\EventListener\CorsListener
        tags:
           - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }