services:
    accesstoken.subscriber:
        class: Zerodine\Bundle\OAuthServerBundle\EventListener\AccessTokenSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }